# Copy this sample file next to the binary to test (e.g. in "./target/release")

[appenders.aws]
kind = "async_web_socket"
server_url = "ws://127.0.0.1:55555" # Make sure to either spawn a web server at this address or
                                    # change this URL.
session_id = "magic-value"

[appenders.display]
kind = "console"

[appenders.async_file]
kind = "async_file"
output_file_name = "The-Safe-CLI.log"
pattern = "{l} {d(%H:%M:%S.%f)} [{M} #FS#{f}#FE#:{L}] {m}{n}"
append = true
# file_timestamp = true

# This will log all levels from log_test into file and web socket.
[loggers."log_test"]
level = "trace"
appenders = ["aws", "async_file"]
additive = false # If true it will also send it to the appenders ("display") of parent ("root").

# This will log from info level from log_test::abc into file and console.
[loggers."log_test::abc"]
level = "info"
appenders = ["display", "async_file"]
additive = false # If true it will also send it to the appenders ("aws") of parent ("log_test").

[root]
level = "error"
appenders = ["async_console", "async_file"]

[loggers."crust"]
level = "trace"

[loggers."routing"]
level = "trace"

[loggers."routing_stats"]
level = "trace"

[loggers."safe_core"]
level = "trace"

[loggers."safe_app"]
level = "trace"

[loggers."safe_authenticator"]
level = "trace"

[loggers."ffi_utils"]
level = "trace"
