[package]
name = "sn_cmd_test_utilities"
version = "1.0.0"
description = "Safe CLI Test Utilities"
authors = ["bochaco <gabrielviganotti@gmail.com>", "Josh Wilson <joshuef@gmail.com>"]
publish = false
license = "MIT OR BSD-3-Clause"
repository = "https://github.com/maidsafe/sn_api"
edition = "2018"

[dependencies]
rand = "~0.7.3"
serde = "1.0.91"
serde_json = "1.0.39"
safe-nd = "~0.11.0"
duct = "~0.12.0"
unwrap = "1.2.1"
walkdir = "2.3.1"
tiny-keccak = "1.5.0"
multibase = "~0.6.0"


[dependencies.sn_api]
path = "../sn_api"
default-features = false
features = ["app", "authd_client"]
