#!/bin/bash

set -e -x

function run_cli_tests() {
    cd sn_cli
    cargo test --release --test cli_keys
    # Temporarily disable running the following tests as they currently
    # need refactoring to account for network sync up periods.
    #cargo test --release --test cli_cat
    #cargo test --release --test cli_dog
    #cargo test --release --test cli_files -- --test-threads=1
    #cargo test --release --test cli_files_get -- --test-threads=1
    #cargo test --release --test cli_wallet
    #cargo test --release --test cli_nrs
    #cargo test --release --test cli_seq
    cd -
}

run_cli_tests
