#!/bin/bash

# Run a baby-fleming network
set -e -x
# Pull in funcs to setup a network
source ./resources/test-scripts/install-vault-and-authd

safe_vault_version=$1

function download_and_run_safe_baby_fleming() {
    # First arg is safe vault desired
    # download_safe_vault $safe_vault_version
    echo "killing any prior vaults"
    # cd safe-cli
    cargo run -- vault killall
    cargo run -- vault run-baby-fleming
    # cd -
}


echo "running baby flem"
download_and_run_safe_baby_fleming
