#!/bin/bash

# Run a baby-fleming network
set -e -x
source ./resources/test-scripts/install-vault-and-authd

[[ -z $SAFE_AUTHD_PATH ]] && export SAFE_AUTHD_PATH=~/safe-authd
[[ -z $SAFE_VAULT_PATH ]] && export SAFE_VAULT_PATH=~/safe-vault

# safe_vault_version=$1
safe_vault_version="0.21.0"
uname_output=$(uname -a)
authd_bin_name="safe-authd"

case $uname_output in
    MSYS_NT*)   # Windows in Jenkins
        authd_bin_name="safe-authd.exe"
        ;;
    MINGW*)     # Windows in GH Actions
        authd_bin_name="safe-authd.exe"
        ;;
esac

function download_and_run_safe_baby_fleming() {
    # First arg is safe vault desired
  download_safe_vault $safe_vault_version
  cargo run -- vault run-baby-fleming
}


function build_safe_authd() {
    cd safe-authd
    cargo build --release

    rm -rf $SAFE_AUTHD_PATH
    mkdir $SAFE_AUTHD_PATH
    mv ../target/release/$authd_bin_name $SAFE_AUTHD_PATH
    pwd
    cd -
}

function run_safe_authd() {
    cd $SAFE_AUTHD_PATH

    # this won't have any effect on Linux/Mac, but it's required for Windows
    ./$authd_bin_name install || true

    echo "Stopping safe-authd daemon.."
    ./$authd_bin_name stop || true

    echo "Launching safe-authd daemon..."
    ./$authd_bin_name start
    sleep 15
    cd -
}

