[package]
name = "sn_api"
version = "0.17.0"
description = "Safe API"
authors = ["bochaco <gabrielviganotti@gmail.com>", "Josh Wilson <joshuef@gmail.com>"]
license = "MIT OR BSD-3-Clause"
repository = "https://github.com/maidsafe/sn_api"
include = ["Cargo.toml", "src/api/*", "src/lib.rs"]
edition = "2018"

[dependencies]
async-std = "1.6.0"
async-trait = "~0.1.24"
ed25519 = "1.0.1"
ed25519-dalek = { version = "1.0.0-pre.4", features = [ "serde" ]}
bincode = "1.2.1"
chrono = "~0.4.6"
dirs-next = "1.0.1"
env_logger = "~0.6.0"
futures = "~0.3.5"
qjsonrpc = { path = "../qjsonrpc", version = "~0.0.9" }
lazy_static = "1.4.0"
log = "~0.4.6"
mime_guess = "2.0.1"
multibase = "~0.8.0"
rand = "~0.7.3"
rand_core = "~0.5.1"
relative-path = "~0.4.0"
sn_client = "~0.44.6"
sn_data_types = "~0.11.39"
serde = "1.0.91"
serde_json = "1.0.41"
threshold_crypto = "~0.4.0"
tiny-keccak = "1.5.0"
tokio = { version = "~0.2.21", features = ["rt-core"] }
url = "2.1.1"
urlencoding = "1.0.0"
walkdir = "2.3.1" #ffi utils needs this version
uhttp_uri = "~0.5.1"
xor_name = "1.1.1"
pbkdf2 = { version = "~0.3.0", default-features = false }
hmac = "~0.7.1"
sha3 = "~0.8.2"

[features]
authenticator = []
authd_client = []
app = []
simulated-payouts = ["sn_client/simulated-payouts"]
default = ["simulated-payouts","authenticator", "authd_client", "app"]

[dev-dependencies]
tokio = { version = "~0.2.21", features = ["macros"] }
proptest = "0.10.1"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false # Disable features which are enabled by default
features = ["precommit-hook","user-hooks"]
