[package]
name = "sn_entropy"
version = "0.1.0"
authors = ["DPC <dylan.dpc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.21"
walkdir = "~2.3.2"
thiserror = "~1.0.24"