name: Mini Network Tests

on: [pull_request, push]

env:
  # Run all cargo commands with --verbose.
  CARGO_TERM_VERBOSE: true
  RUST_BACKTRACE: 1
  SAFE_VAULT_VERSION: "0.24.0"
  # Deny all compiler warnings.
  RUSTFLAGS: "-D warnings"

jobs:
  network-test:
    name: E2E against real baby
    runs-on: ubuntu-latest
    if: false
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: mkdir -p ~/.safe/vault
      - name: dl vault
        run: wget https://github.com/maidsafe/safe_vault/releases/download/${{env.SAFE_VAULT_VERSION}}/safe_vault-${{env.SAFE_VAULT_VERSION}}-x86_64-unknown-linux-musl.zip
      - run: unzip safe_vault-${{env.SAFE_VAULT_VERSION}}-x86_64-unknown-linux-musl.zip -d $HOME/.safe/vault
      - name: Build
        run: cargo build --release
      - name: Setup Safe Cli and PATH etc
        run: |
          mkdir -p ~/.safe/cli
          mkdir -p ~/.safe/authd
          cp ./target/release/safe $HOME/.safe/cli/
          cp ./target/release/safe-authd $HOME/.safe/authd/
          ls $HOME/.safe/cli
          ls $HOME/.safe/authd
          echo "::add-path::$HOME/.safe/cli"
          echo "::add-path::$HOME/.safe/authd"
          echo $PATH
          chmod +x $HOME/.safe/authd/safe-authd
          chmod +x $HOME/.safe/cli/safe
          chmod +x $HOME/.safe/vault/safe_vault
      - name: Setup The Baby
        run : safe vault run-baby-fleming -t
      - name: Run Tests
        run: ./resources/test-scripts/cli-network-tests
        shell: bash

      - name: Stop the network.
        if: failure()
        run: safe vault killall || true && safe auth stop || true

      - name: Failure logs.
        if: failure()
        run: tail $HOME/.safe/vault/baby-fleming-vaults/*/*.log

  network-latest-vault-test:
    name: E2E against real baby with latest non-released vault
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Clone safe-vault
        run: git clone https://github.com/maidsafe/safe-vault.git $HOME/.safe/vault
      - name: Build safe-vault
        run: cargo build --release --manifest-path=$HOME/.safe/vault/Cargo.toml
      - run: cp $HOME/.safe/vault/target/release/safe_vault $HOME/.safe/vault/
      - name: Build Safe CLI and sn_authd
        run: cargo build --release
      - name: Setup Safe CLI and PATH etc
        run: |
          mkdir -p ~/.safe/cli
          mkdir -p ~/.safe/authd
          cp ./target/release/safe $HOME/.safe/cli/
          cp ./target/release/safe-authd $HOME/.safe/authd/
          ls $HOME/.safe/cli
          ls $HOME/.safe/authd
          echo "::add-path::$HOME/.safe/cli"
          echo "::add-path::$HOME/.safe/authd"
          echo $PATH
          chmod +x $HOME/.safe/authd/safe-authd
          chmod +x $HOME/.safe/cli/safe
          chmod +x $HOME/.safe/vault/safe_vault
      - name: Setup The Baby
        run : safe vault run-baby-fleming -t
      - name: Run CLI Tests
        run: ./resources/test-scripts/cli-network-tests
        shell: bash
      - name: Run sn_api Tests
        run: ./resources/test-scripts/api-network-tests
        shell: bash

      - name: Stop the network.
        if: failure()
        run: safe vault killall || true && safe auth stop || true

      - name: Failure safe-vault logs.
        if: failure()
        run: tail $HOME/.safe/vault/baby-fleming-vaults/*/*.log

      - name: Failure sn_authd logs.
        if: failure()
        run: tail $HOME/.safe/authd/logs/safe-authd.log
